In [1]:
import numpy as np
a1=np.array([[1,5,7,3],[2,5,9,4],[1,3,4,6]])
print(a1)
print(a1.shape)   #R,C   
print("Print me 2nd index and 3rd value",a1[1][2])
#print(np.arange(10))   # Its like range but u can use in numpy only, better optimization then range
print(a1.ndim)   # dimension
len(a1)  # Total no of records

[[1 5 7 3]
 [2 5 9 4]
 [1 3 4 6]]
(3, 4)
Print me 2nd index and 3rd value 9
2


3

In [4]:
a=np.array([1,5,7])    # row vector
#a=np.array([[1,5,7]])   # 2d array
print(a)
print(a.ndim)
print(a.shape)    # only row, there is no column

[1 5 7]
1
(3,)


In [ ]:
# Python Lists
L=range(1000)
%timeit[i**2 for i in L]


In [6]:
a=np.array([[9,3,3],[1,3,6]])
#a=np.array([[9,3,3],[1,3,]])

print(a)
print(a.ndim)
print(a.shape)

[[9 3 3]
 [1 3 6]]
2
(2, 3)


In [7]:
a[1][1]=6
print(a)

[[9 3 3]
 [1 6 6]]


In [8]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a=np.arange(1,10,3)
a

array([1, 4, 7])

In [11]:
#using linespace
ls=np.linspace(1,2,6)
ls

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [13]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.diag(a)

array([[-1,  0,  0,  0],
       [ 0, -1,  0,  0],
       [ 0,  0,  4,  0],
       [ 0,  0,  0,  4]])

In [18]:
#Fancy Indexing
#OTP encoding
import numpy as np
a=np.random.randint(0,9,4)
a

array([3, 1, 4, 4])

In [19]:
mask=(a%2 == 1)
mask

array([ True,  True, False, False])

In [20]:
output_of_a=a[mask]
output_of_a

array([3, 1])

In [21]:
a[mask]=-1     # OTP encoding
a

array([-1, -1,  4,  4])

In [23]:
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [24]:
a[[2,3,2,4,2]]      #multi access at a time

array([20, 30, 20, 40, 20])

In [26]:
a[[2,5,7]]=-200    #Replacing the values at a time. It is possible only in numpy.
a

array([   0,   10, -200,   30,   40, -200,   60, -200,   80,   90])

In [27]:
import pandas as pd 
#df=pd.read_csv(nyc_whether.csv)
#df

In [28]:

# Creating a dataframe

weather_data=[('1/1/2017','32','6','Rain'),     #list of tuples
              ('1/2/2017','-99999','7','Sunny'),
              ('1/3/2017','28',-99999,'snow'),
              ('1/4/2017','-99999','7','0'),
              ('1/5/2017','32','-99999','Rain'),
              ('1/6/2017',31,2,'Sunny'),
              ('1/6/2027','34','5',0)
              ]
df1=pd.DataFrame(weather_data,columns=['day','temp','wspeed','event'])
df1


day    temp  wspeed  event
0  1/1/2017      32       6   Rain
1  1/2/2017  -99999       7  Sunny
2  1/3/2017      28  -99999   snow
3  1/4/2017  -99999       7      0
4  1/5/2017      32  -99999   Rain
5  1/6/2017      31       2  Sunny
6  1/6/2027      34       5      0

In [31]:
#df1.count
#df1.columns
df1.describe()

day temp wspeed event
count          7    7      7     7
unique         7    5      6     5
top     1/1/2017   32      7  Rain
freq           1    2      2     2